/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frecuencias;
import AcercaDe.AcercaDe;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import VariableContinua.*;
import VariableDiscreta.*;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;



/**
 *
 * @author JL
 * Terminado: 11/02/2015
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    double vector[];
    public static double vect[]=new double[200];
    static int m;
    static int n;
    boolean sw=false;
    public VentanaPrincipal()
    {
        
        initComponents();
        this.setTitle("Frecuencias Estadísticas   v1.0.4");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        insertImage();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Multimedia/Icono_1.png"));
        setIconImage(icon);
        soloNumero(txtNum);
        if(!SplashSc.cerrar2())
        {
            cerrar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnDeterminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FRECUENCIAS");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° de Datos: ");

        txtNum.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumFocusLost(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/in1.png"))); // NOI18N
        btnAgregar.setText("Agregar Datos         ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnDeterminar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeterminar.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        btnDeterminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/d1.png"))); // NOI18N
        btnDeterminar.setText("Determinar Variable");
        btnDeterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeterminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDeterminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addComponent(btnAgregar)
                .addGap(26, 26, 26)
                .addComponent(btnDeterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(false);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ic2.png"))); // NOI18N
        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        MenuSalir.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        MenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ic3.jpg"))); // NOI18N
        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ic1.jpg"))); // NOI18N
        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        MenuAcercaDe.setBackground(new java.awt.Color(255, 255, 255));
        MenuAcercaDe.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        MenuAcercaDe.setText("Acerca De");
        MenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        JOptionPane.showMessageDialog(null,"Gracias por usar el Sistema");
        System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        if(txtNum.getText().equals("") || Integer.parseInt(txtNum.getText())<=0)
        {
            JOptionPane.showMessageDialog(null, "No se ha ingresado un valor válido...\nVuelva a Ingresar","Error",JOptionPane.ERROR_MESSAGE);
            txtNum.requestFocus();
            txtNum.setText("");
        }else{
            vector=new double[n];
            vect=new double[n];
            ProcesosMain obj=new ProcesosMain();
            n=Integer.parseInt(txtNum.getText());
            vector=obj.ingresoDatos(n);
            vect=obj.vectorDATOS();
            //*********************************+Comprobando vector....
            for (int i = 0; i < n; i++) 
            {
                System.out.print("["+vect[i]+"]");
            }
            System.out.println("-------------------------");
            sw=true;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnDeterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeterminarActionPerformed
        
        if(!sw)
        {
            JOptionPane.showMessageDialog(null, "No se han Ingresado Datos...","Error",JOptionPane.ERROR_MESSAGE);
        }else{
        ProcesosMain obj=new ProcesosMain();
        System.out.println("\n\nVector Original1");
        obj.imprimir(vector);
        m=obj.valorM(vect);
        System.out.println(m);
        
        
        if(m<=11)
        {
            VentanaVDiscreta dialog=new VentanaVDiscreta(new javax.swing.JFrame(),true);
            JOptionPane.showMessageDialog(null,"Datos Diferentes: "+m+"\nEs Variable Discreta");
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }else
            {
                
                VentanaVContinua dialog1=new VentanaVContinua(new javax.swing.JFrame(),true);
                JOptionPane.showMessageDialog(null,"Datos Diferentes: "+m+"\nEs Variable Continua");
                dialog1.setLocationRelativeTo(null);
                dialog1.setVisible(true);
            }
        }
    txtNum.setText("");
    vector=null;
    vect=null;
    n=0;
    m=0;
    txtNum.requestFocus();
    }//GEN-LAST:event_btnDeterminarActionPerformed

    private void MenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcercaDeActionPerformed
        AcercaDe dialog=new AcercaDe(new javax.swing.JFrame(),true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_MenuAcercaDeActionPerformed

    private void txtNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFocusLost
       
    }//GEN-LAST:event_txtNumFocusLost
    public static double[] vectorDatos()
    {
        return vect;
    }
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        jPanel1.add(Imagen);
        jPanel1.repaint();
    }
    public static int valorN()
    {
        return n;
    }
    public static int valorM()
    {
        return m;
    }  
    public void soloNumero(JTextField txt)
    {
        txt.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!Character.isDigit(c))
                {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    public void confirmarSalida()
    {
        int valor=JOptionPane.showConfirmDialog(this,"¿Esta seguro de cerrar la Ventana?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==0)
        {
            JOptionPane.showMessageDialog(null, "Hasta Pronto...","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    confirmarSalida();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Thread(new SplashSc()).start();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(500,500);
        }
    @Override
    public void paint(Graphics grafico)
    {
        Dimension height = getSize();
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
        ImageIcon Img = new ImageIcon(getClass().getResource("/Multimedia/fm.jpg")); 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAcercaDe;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeterminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
