/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VariableDiscreta;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import Frecuencias.*;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;



/**
 *
 * @author JL
 */
public class VentanaVDiscreta extends javax.swing.JDialog {

    /**
     * Creates new form VDiscreta
     */
    double vector[];
    DefaultTableModel modelo;
    Object datos[][]={}; 
    
    public VentanaVDiscreta(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Multimedia/iconoVD.jpg"));
        setIconImage(icon);
        
        this.setTitle("Variable Discreta");
        initComponents();
        insertImage();
        this.setLocationRelativeTo(null);
        String cabecera[]={"i","Xi","ni","Ni","hi","Hi"};
        
        modelo=new DefaultTableModel(datos,cabecera);
        Tabla.setModel(modelo);  
        
        generarVDiscreta();
        editarCabecera();
    
    }
    public void generarVDiscreta()
     {
        vector=new double[VentanaPrincipal.valorN()];
        Procesos obj=new Procesos();
        vector=VentanaPrincipal.vect;
        System.out.println("Vect Retornado");
        obj.imprimir(vector);//Ver todo el vector*/
        ArrayList<VDiscreta> lstVd=new ArrayList<VDiscreta>();
        lstVd=obj.variableDiscreta(vector);//ArrayList con valores de xi,ni
        int m=obj.valorM();//Valor de M
        VDiscreta vd[]=new VDiscreta[m];
        obj.imprimirVD(m, obj.vectVd(m, vd));//Ver valores Vector Objeto Variable Discreta
        VDiscreta vectorOrd[]=obj.vectOrd(m, vd);
        //------------------------------------------Columnas
        double vectNI[]=obj.columnaNI(m, vectorOrd);
        double vecthi[]=obj.columnahi(VentanaPrincipal.valorN(), vectorOrd);
        double vectHI[]=obj.columnaHI(m, vecthi);
        
        //------------------------------------------
        //Mostrar Tabla Variable Discreta
        for(int j=1;j<=m;j++)
        {    
            Object[]fila= new Object[6];
            for(int i=0;i<6;i++)
            {
                fila[0]=j;
                fila[1]=vectorOrd[j-1].getXi();
                fila[2]=vectorOrd[j-1].getNi();
                fila[3]=vectNI[j-1];
                fila[4]=formatoTotal(vecthi[j-1]).toString().replace(",", ".");
                fila[5]=formatoTotal(vectHI[j-1]).toString().replace(",", ".");;
            }
            modelo.addRow(fila);
        }
        txtIndice.setText(modelo.getValueAt(0,0)+"");
        double hi=Double.parseDouble(modelo.getValueAt(0,4).toString().replace(",","."))*100;
        txtValorhi.setText(formato2D(hi).replace(",",".")+" %");
        double Hi=Double.parseDouble(modelo.getValueAt(0,5).toString().replace(",","."))*100;
        txtValorHi.setText(formato2D(Hi).replace(",",".")+" %");
     }
    
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        jPanel1.add(Imagen);
        jPanel1.repaint();
    }
    public String formatoTotal(double valor)
    {
        DecimalFormat dfTotal=new DecimalFormat("0.000");
        return dfTotal.format(valor);
    }
    public String formato2D(double valor)
    {
        DecimalFormat dfTotal=new DecimalFormat("0.00");
        return dfTotal.format(valor);
    }
    public void editarCabecera()
    {
        JTableHeader th; 
        th = Tabla.getTableHeader(); 
        Font fuente = new Font("BankGothic Lt BT", Font.BOLD, 13); 
        th.setFont(fuente); 
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        txtValorhi = new javax.swing.JTextField();
        txtValorHi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnGrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel1.setText("VARIABLE DISCRETA");

        Tabla.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(255, 255, 255));
        Tabla.setSelectionBackground(new java.awt.Color(204, 204, 204));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        jLabel2.setText("Indice N°: ");

        jLabel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        jLabel4.setText("Valor hi: ");

        jLabel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 13)); // NOI18N
        jLabel5.setText("Valor Hi:");

        txtIndice.setEditable(false);
        txtIndice.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txtValorhi.setEditable(false);
        txtValorhi.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txtValorHi.setEditable(false);
        txtValorHi.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnGrafica.setBackground(new java.awt.Color(255, 255, 255));
        btnGrafica.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        btnGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icoG.png"))); // NOI18N
        btnGrafica.setText("Gráfica");
        btnGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrafica.setIconTextGap(-3);
        btnGrafica.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorHi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorhi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrafica)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtValorhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorHi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        txtIndice.setText(modelo.getValueAt(Tabla.getSelectedRow(),0)+"");
        
        double hi=Double.parseDouble(modelo.getValueAt(Tabla.getSelectedRow(),4).toString().replace(",","."))*100;
        txtValorhi.setText(formato2D(hi).replace(",",".")+" %");
        double Hi=Double.parseDouble(modelo.getValueAt(Tabla.getSelectedRow(),5).toString().replace(",","."))*100;
        txtValorHi.setText(formato2D(Hi).replace(",",".")+" %");
    }//GEN-LAST:event_TablaMouseClicked

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        GraficaVD dialog=new GraficaVD(new javax.swing.JFrame(),true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnGraficaActionPerformed

    
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(460,382);
        }
        @Override
        public void paint(Graphics grafico)
        {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Multimedia/fios2.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtValorHi;
    private javax.swing.JTextField txtValorhi;
    // End of variables declaration//GEN-END:variables
}
